---
numberOfBrokers: 3
interval: 3
standardIsr: 2
reducedIsr: 1
countToSwitch: 2
kafkaProperties:
  bootstrap.servers: "172.31.0.6:29092,172.31.0.5:29093,172.31.0.7:29094"
  security.protocol: "SSL"
  ssl.truststore.location: "/home/greg/work/kafka-heartbeat/secrets/kafka_truststore.jks"
  ssl.truststore.password: "confluent"
  ssl.keystore.location: "/home/greg/work/kafka-heartbeat/secrets/kafka_keystore.jks"
  ssl.keystore.password: "confluent"
  ssl.key.password: "confluent"
  ssl.endpoint.identification.algorithm: " "
  ssl.test.yaml.property: "ssl-test-yaml-property"
topics:
  - greg-test1
  - greg-test2
